### PR TITLE
bugfix: wrong context menu initialization (fix #58)

### LINKED ISSUE #58: Wrong initialization context menu in tree
## Version
@version 4.0.0
## Development Environment
Opera, Windows

## Current Behavior
Menu container created in html body automatically and not found custom prepared container. 

```js
In src/js/features/contextMenu.js

 /**
       * Id of floating layer in tree
       * @type {string}
       */
      this.flId = containerId + '-fl';

      /**
       * Info of context menu in tree
       * @type {Object}
       */
      this.menu = this._generateContextMenu(options.usageStatistics);

      /**
       * Floating layer element
       * @type {HTMLElement}
       */
      this.flElement = document.getElementById(this.flId);

```
this.flElement = document.getElementById(this.flId); must be above this._generateContextMenu(options.usageStatistics); because it use this.flElement !!! 
the element(this.flElement) is always empty and is recreated in the body from generateContextMenu() function!!

## Expected Behavior
I could use custom menu container, for example: 
```html
<div id='listEditor' class='tui-tree-wrap' ></div>
<div id='listEditor-fl'></div>
```
But in current behavior it impossible.

### PR DESCRIPTION
**Pull request by lightway82**
Note: I created PR to master because there is no develop branch available.

### CODE REVIEW

**Comment by seonim-ryu** [comment]
Can one of the admins verify this patch?

**Comment by lightway82** [comment]
In tui.context-menu in contextmenu.js:
`
this.activeLayer = relatedLayer;
const position = getMousePosition(clickEvent, document.body || document.documentElement);
`

need calculate position from this.activeLayer:
const position = getMousePosition(clickEvent, this.activeLayer);

**Comment by seonim-ryu** [comment]
@lightway82 
> I build fix and it work. I show context menu in my modal window( use custom menu container in modal window), but menu showing in incorrect position(calculating position from document or body)
> 
> Then I use default behavior with container in body and use css , because context menu showing under modal window :
> 
> ```
> .floating-layer{
>  z-index: 10000;
> }
> ```
> 
> but need make changes in tui.context-menu in contextmenu.js for correct using custom container for ctx.menu:
> 
> ```
> this.activeLayer = relatedLayer;
> 
> const position = getMousePosition(clickEvent, document.body || document.documentElement);
> ```
> 
> need calculate position from this.activeLayer:
> const position = getMousePosition(clickEvent, this.activeLayer);

Could you show a screenshot of this issue or example code when creating a modal window? Just by looking at this, I can't confirm how the position was wrong. And if it's a problem of the context menu component, I would appreciate it if you register this issue in the context menu repository.

**Comment by seonim-ryu** [comment]
ok to test

**Comment by dotaitch** [comment]
ok to test

**Comment by lja1018** [comment]
ok to test

**Comment by lja1018** [comment]
@lightway82 
This issue is solved by #62 .
So, let's update tui.tree to v4.0.1
Thank you for your attention.

**Pull request closed without merging**
