### PR TITLE
fix: change mouse move, out, up handler name

### PR DESCRIPTION
**Pull request by lja1018**
change mouse move, out, up handler name

### CODE REVIEW

**Review by dotaitch — APPROVED** [review]
[8/25] 리뷰 완료합니다 👍

**Comment by lja1018** [comment]
ok to test

**Comment by lja1018** [comment]
ok to test

**Comment by lja1018** [comment]
ok to test

**Comment by lja1018** [comment]
ok to test

**Comment by lja1018** [comment]
ok to test

**Pull request merged**
